# This provides metadata for NIH-plug's `cargo xtask bundle <foo>` plugin
# bundler. This file's syntax is as follows:
#
# [package_name]
# name = "Human Readable Plugin Name"  # defaults to <package_name>

[toybox]
name = "Toybox"

[orchestron]
name = "Orchestron"

[bells]
name = "Bells"
private = true
