[package]
name = "config"
edition.workspace = true
authors.workspace = true
license = "MIT"

[dependencies]
config_macro = { path = "../config_macro", optional = true }
serde = { workspace = true }
toml = { workspace = true }

[features]
macro = ["dep:config_macro"]
