const presets = [
  { value: "Accordion", name: "Accordion" },
  { value: "AltoSax", name: "Alto Sax" },
  { value: "Bandoneon", name: "Bandoneon" },
  { value: "Brass1", name: "Brass 1" },
  { value: "Brass2", name: "Brass 2" },
  { value: "BrassEnsemble", name: "Brass Ensemble" },
  { value: "Cello", name: "Cello" },
  { value: "ChurchOrgan", name: "Church Organ" },
  { value: "Clarinet", name: "Clarinet" },
  { value: "ElecOrgan1", name: "Electric Organ 1" },
  { value: "ElecOrgan2", name: "Electric Organ 2" },
  { value: "ElecOrgan3", name: "Electric Organ 3" },
  { value: "ElecOrgan4", name: "Electric Organ 4" },
  { value: "Flute", name: "Flute" },
  { value: "FrenchHorn1", name: "French Horn 1" },
  { value: "FrenchHorn2", name: "French Horn 2" },
  { value: "Harmonica", name: "Harmonica" },
  { value: "Harp", name: "Harp" },
  { value: "Oboe", name: "Oboe" },
  { value: "Piccolo", name: "Piccolo" },
  { value: "PipeOrgan", name: "Pipe Organ" },
  { value: "Recorder", name: "Recorder" },
  { value: "ReedOrgan", name: "Reed Organ" },
  { value: "SopranoSax", name: "SopranoSax" },
  { value: "Soundtrack", name: "Soundtrack" },
  { value: "Strings1", name: "Strings 1" },
  { value: "Strings2", name: "Strings 2" },
  { value: "Strings3", name: "Strings 3" },
  { value: "SynPad1", name: "Synth Pad 1" },
  { value: "SynPad2", name: "Synth Pad 2" },
  { value: "SynPad3", name: "Synth Pad 3" },
  { value: "TenorSax", name: "Tenor Sax" },
  { value: "Trumpet", name: "Trumpet" },
  { value: "Tuba", name: "Tuba" },
  { value: "Violin", name: "Violin" },
];

export default presets;
