[package]
name = "config_macro"
edition.workspace = true
authors.workspace = true
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
serde = { workspace = true }
toml = { workspace = true }
cargo_metadata = "0.23.0"
