[package]
name = "ci"
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.23.0"
clap = { version = "4.5", features = ["derive"] }
config = { workspace = true }
nih_plug_xtask = { workspace = true }
toml = { workspace = true }
