[alias]
xtask = "run --package xtask --release --"
ci = "xtask bundle -p toybox -p orchestron -p bells --release"

[env]
SAMPLES = { value = "samples/", relative = true }
PKG_EMAIL = { value = "info@zmann.org" }
PKG_VENDOR = { value = "ZMANN" }
