[alias]
xtask = "run --package xtask --release --"
ci = "run --package ci --release --"

[env]
SAMPLES = { value = "samples/", relative = true }
PKG_EMAIL = { value = "info@zmann.org" }
PKG_VENDOR = { value = "ZMANN" }
