[package]
name = "common"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
dasp = { version = "0.11", features = [
    "signal",
    "interpolate-linear",
    "interpolate",
] }
hound = "3.5"
