[package]
name = "ci"
edition.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
nih_plug_xtask = { git = "https://github.com/robbert-vdh/nih-plug.git" }
cargo_metadata = "0.23.0"
toml = "0.9.8"
serde = { version = "1.0", features = ["derive"] }
